import React, { useEffect, useMemo, useState } from "react";
import { Search, RefreshCw } from "lucide-react";
import { MiniLineChart } from "../CandlestickChart";
import { TimeSeriesChart } from "../TimeSeriesChart";

const fmt = (value: number | null | undefined, digits = 4) => value == null ? '—' : value.toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits});

export function ForeignExchangeTab() {
  const [items,setItems]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null);
  const [region,setRegion]=useState('All'); const [country,setCountry]=useState('All'); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/fx');const body=await response.json();if(!response.ok)throw new Error(body.error||`API ${response.status}`);setItems(body.items||[]);setSelected((current:any)=>current&&body.items?.find((item:any)=>item.id===current.id)||body.items?.[0]||null);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const regions=useMemo(()=>['All',...Array.from(new Set(items.map(item=>item.category||'Other'))).sort()], [items]);
  const countries=useMemo(()=>['All',...Array.from(new Set(items.filter(item=>region==='All'||item.category===region).map(item=>item.countryName||item.country||'Global'))).sort()], [items,region]);
  const filtered=useMemo(()=>items.filter(item=>(region==='All'||item.category===region)&&(country==='All'||(item.countryName||item.country||'Global')===country)&&(!query||`${item.name} ${item.symbol}`.toLowerCase().includes(query.toLowerCase()))),[items,region,country,query]);
  const ohlc=selected?.ohlc||[]; const up=(selected?.changePct??0)>=0;
  return <div className="p-4 space-y-4 max-w-screen-2xl mx-auto">
    <section className="bg-card border border-border rounded overflow-hidden"><div className="p-4 bg-secondary/40 border-b border-border flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">Global Foreign Exchange</h2><p className="text-[10px] text-muted-foreground mt-1">Spot and index pricing from DuckDB · {items.length} live series</p></div><div className="flex gap-2"><label className="flex items-center gap-2 bg-background border border-border rounded px-3"><Search size={13}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search currency…" className="bg-transparent outline-none text-xs py-2"/></label><button onClick={load} className="p-2 border border-border rounded hover:bg-secondary"><RefreshCw size={13} className={loading?'animate-spin':''}/></button></div></div>
      <div className="p-3 space-y-2"><div className="flex items-start gap-3"><span className="w-16 pt-1 text-[10px] uppercase text-muted-foreground">Region</span><div className="flex flex-wrap gap-1.5">{regions.map(value=><button key={value} onClick={()=>{setRegion(value);setCountry('All');}} className={`px-2.5 py-1 rounded border text-[10px] ${region===value?'bg-primary text-white border-primary':'border-border text-muted-foreground'}`}>{value}</button>)}</div></div><div className="flex items-start gap-3"><span className="w-16 pt-1 text-[10px] uppercase text-muted-foreground">Country</span><div className="flex flex-wrap gap-1.5">{countries.map(value=><button key={value} onClick={()=>setCountry(value)} className={`px-2.5 py-1 rounded border text-[10px] ${country===value?'bg-accent text-primary border-primary':'border-border text-muted-foreground'}`}>{value}</button>)}</div></div></div>
    </section>
    {error&&<div className="p-3 border border-down/30 bg-down/5 text-down rounded text-xs">{error}</div>}
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
      <div className="xl:col-span-2 bg-card border border-border rounded overflow-hidden"><div className="px-3 py-2 bg-secondary border-b border-border flex justify-between text-[10px] text-muted-foreground"><span>{filtered.length} matching instruments</span><span>Maximum 10 visible rows</span></div><div className="max-h-[443px] overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 z-10 bg-secondary"><tr>{['Currency','Region','Country','Last','Change','Change %','Trend'].map(label=><th key={label} className="px-3 py-2 text-left text-muted-foreground">{label}</th>)}</tr></thead><tbody>{filtered.map(item=>{const positive=item.changePct>=0;return <tr key={item.id} onClick={()=>setSelected(item)} className={`border-t border-border cursor-pointer ${selected?.id===item.id?'bg-accent':'hover:bg-secondary/60'}`}><td className="px-3 py-2"><div className="font-semibold">{item.name}</div><div className="text-[9px] font-mono text-muted-foreground">{item.symbol}</div></td><td className="px-3 py-2 text-muted-foreground">{item.category}</td><td className="px-3 py-2"><span className="mr-1">{item.flag}</span>{item.countryName}</td><td className="px-3 py-2 font-mono font-bold">{fmt(item.value)}</td><td className={`px-3 py-2 font-mono ${positive?'text-up':'text-down'}`}>{positive?'+':''}{fmt(item.change)}</td><td className={`px-3 py-2 font-mono font-bold ${positive?'text-up':'text-down'}`}>{positive?'+':''}{fmt(item.changePct,2)}%</td><td className="px-3 py-2"><MiniLineChart data={item.trend.slice(-30)} width={80} height={25} color={positive?'#16A34A':'#DC2626'} fill={false}/></td></tr>})}</tbody></table></div></div>
      <aside className="bg-card border border-border rounded p-4">{selected?<><div className="flex justify-between"><div><span className="text-xl">{selected.flag}</span><h3 className="text-sm font-bold mt-1">{selected.name}</h3><p className="text-[10px] text-muted-foreground mt-1">{selected.symbol} · {selected.category}</p></div><div className="text-right"><div className="text-xl font-mono font-bold">{fmt(selected.value)}</div><div className={`text-xs font-mono ${up?'text-up':'text-down'}`}>{up?'+':''}{fmt(selected.changePct,2)}%</div></div></div><div className="grid grid-cols-2 gap-2 mt-4">{[['Session High',selected.high],['Session Low',selected.low],['Previous',selected.prev],['As of',selected.asOf]].map(([label,value])=><div key={String(label)} className="bg-secondary rounded p-2"><div className="text-[9px] text-muted-foreground">{label}</div><div className="text-xs font-mono font-semibold mt-1">{typeof value==='number'?fmt(value):String(value??'—')}</div></div>)}</div></>:<div className="text-xs text-muted-foreground">Select a currency instrument.</div>}</aside>
    </div>
    {selected&&<section className="bg-card border border-border rounded p-4"><div className="mb-3"><h3 className="text-sm font-bold">{selected.name} Price History</h3><p className="text-[10px] text-muted-foreground mt-1">Full OHLC history · Default view: latest 3 months</p></div><TimeSeriesChart key={selected.id} data={ohlc} height={500} initialMode="candle" initialMonths={3}/></section>}
  </div>;
}
