macro_jobs:
  - input_path: "data_lake/macro/USA/USCPI YoY.xlsx"
    output_path: "data_warehouse/raw/macro/USA/USCPI_YoY.parquet"
    symbol: "CPIYOY"
    exchange: "BOL"
    country: "United States"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/Nonfarm_Payrolls.parquet"
    symbol: "PAYEMS"
    exchange: "BOL"
    country: "United States"
    sheet_name: "PAYEMS"
  - input_path: "data_lake/macro/USA/USPMI.xlsx"
    output_path: "data_warehouse/raw/macro/USA/NAPMPMI.parquet"
    symbol: "NAPMPMI"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMPMI"
  - input_path: "data_lake/macro/USA/USPMI.xlsx"
    output_path: "data_warehouse/raw/macro/USA/NAPMNEWO.parquet"
    symbol: "NAPMNEWO"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNEWO"
  - input_path: "data_lake/macro/USA/USPMI.xlsx"
    output_path: "data_warehouse/raw/macro/USA/NAPMNMI.parquet"
    symbol: "NAPMNMI"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNMI"
  - input_path: "data_lake/macro/USA/USPMI.xlsx"
    output_path: "data_warehouse/raw/macro/USA/NAPMNNO.parquet"
    symbol: "NAPMNNO"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNNO"
  - input_path: "data_lake/macro/USA/USPMI.xlsx"
    output_path: "data_warehouse/raw/macro/USA/NAPMNSD.parquet"
    symbol: "NAPMNSD"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNSD"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/ADPCHNG.parquet"
    symbol: "ADPCHNG"
    exchange: "ADP"
    country: "United States"
    sheet_name: "ADPCHNG"
  - input_path: "data_lake/macro/USA/FED Target Rate.xlsx"
    output_path: "data_warehouse/raw/macro/USA/FDTR.parquet"
    symbol: "FDTR"
    exchange: "FED"
    country: "United States"
  - input_path: "data_lake/macro/USA/US Consumer Confidence.xlsx"
    output_path: "data_warehouse/raw/macro/USA/CONCCONF.parquet"
    symbol: "CONCCONF"
    exchange: "CB"
    country: "United States"
  - input_path: "data_lake/macro/USA/US Consumer Sentiment.xlsx"
    output_path: "data_warehouse/raw/macro/USA/CONSSENT.parquet"
    symbol: "CONSSENT"
    exchange: "MICHIGAN"
    country: "United States"
  - input_path: "data_lake/macro/USA/US PCE.xlsx"
    output_path: "data_warehouse/raw/macro/USA/PCECYOY.parquet"
    symbol: "PCECYOY"
    exchange: "BEA"
    country: "United States"
    sheet_name: "PCECYOY"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/USURTOT.parquet"
    symbol: "USURTOT"
    exchange: "BOL"
    country: "United States"
    sheet_name: "USURTOT"
  - input_path: "data_lake/macro/USA/USGDP.xlsx"
    output_path: "data_warehouse/raw/macro/USA/GDPCQQQ.parquet"
    symbol: "GDPCQQQ"
    exchange: "BEA"
    country: "United States"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/JOLTTOTL.parquet"
    symbol: "JOLTTOTL"
    exchange: "BOL"
    country: "United States"
    sheet_name: "JOLTTOTL"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/INJCJC.parquet"
    symbol: "INJCJC"
    exchange: "DOL"
    country: "United States"
    sheet_name: "INJCJC"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/AHEMOM.parquet"
    symbol: "AHEMOM"
    exchange: "BLS"
    country: "United States"
    sheet_name: "AHEMOM"
  - input_path: "data_lake/macro/USA/Employments.xlsx"
    output_path: "data_warehouse/raw/macro/USA/AHEYOY.parquet"
    symbol: "AHEYOY"
    exchange: "BLS"
    country: "United States"
    sheet_name: "AHEYOY"
  - input_path: "data_lake/macro/USA/US Goods Order.xlsx"
    output_path: "data_warehouse/raw/macro/USA/DGNOCHNG.parquet"
    symbol: "DGNOCHNG"
    exchange: "USCB"
    country: "United States"
    sheet_name: "DGNOCHNG"
  - input_path: "data_lake/macro/USA/US Goods Order.xlsx"
    output_path: "data_warehouse/raw/macro/USA/DGNOXTCH.parquet"
    symbol: "DGNOXTCH"
    exchange: "USCB"
    country: "United States"
    sheet_name: "DGNOXTCH"

# Europe
  - input_path: "data_lake/macro/Europe/CPI.xlsx"
    output_path: "data_warehouse/raw/macro/Europe/CPICEMU.parquet"
    symbol: "CPICEMU"
    exchange: "EUROSTAT"
    country: "Europe"
    sheet_name: "CPICEMU"
  - input_path: "data_lake/macro/Europe/Employment.xlsx"
    output_path: "data_warehouse/raw/macro/Europe/EURUEMEM.parquet"
    symbol: "EURUEMEM"
    exchange: "EUROSTAT"
    country: "Europe"
    sheet_name: "EURUEMEM"
  - input_path: "data_lake/macro/Europe/Interest Rate.xlsx"
    output_path: "data_warehouse/raw/macro/Europe/EUAPRRT.parquet"
    symbol: "EUAPRRT"
    exchange: "ECB"
    country: "Europe"
    sheet_name: "EUAPRRT"
  - input_path: "data_lake/macro/Europe/GDP.xlsx"
    output_path: "data_warehouse/raw/macro/Europe/EUGDEMU.parquet"
    symbol: "EUGDEMU"
    exchange: "EUROSTAT"
    country: "Europe"
    sheet_name: "EUGDEMU"
  - input_path: "data_lake/macro/Europe/GDP.xlsx"
    output_path: "data_warehouse/raw/macro/Europe/EUGNEMUY.parquet"
    symbol: "EUGNEMUY"
    exchange: "EUROSTAT"
    country: "Europe"
    sheet_name: "EUGNEMUY"

# South Korea
  - input_path: "data_lake/macro/South Korea/Consumer Price Index.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/.parquet"
    symbol: "KOCPIY"
    exchange: "KSTAT"
    country: "South Korea"
  - input_path: "data_lake/macro/South Korea/Export.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/KOEXTOTY.parquet"
    symbol: "KOEXTOTY"
    exchange: "KSTAT"
    country: "South Korea"
  - input_path: "data_lake/macro/South Korea/Retail Sales.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/KORSLM.parquet"
    symbol: "KORSLM"
    exchange: "KSTAT"
    country: "South Korea"
    sheet_name: "KORSLM"
  - input_path: "data_lake/macro/South Korea/Interest.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/KORP7DR.parquet"
    symbol: "KORP7DR"
    exchange: "BOK"
    country: "South Korea"
  - input_path: "data_lake/macro/South Korea/M2.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/KOM2Y.parquet"
    symbol: "KOM2Y"
    exchange: "BOK"
    country: "South Korea"
  - input_path: "data_lake/macro/South Korea/Industrial Production.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/KORPOMOM.parquet"
    symbol: "KORPOMOM"
    exchange: "KSTAT"
    country: "South Korea"
    sheet_name: "KORPOMOM"
  - input_path: "data_lake/macro/South Korea/Industrial Production.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/KORPIYOY.parquet"
    symbol: "KORPIYOY"
    exchange: "KSTAT"
    country: "South Korea"
    sheet_name: "KORPIYOY"
  - input_path: "data_lake/macro/South Korea/Confidence.xlsx"
    output_path: "data_warehouse/raw/macro/South Korea/SKCCSI.parquet"
    symbol: "SKCCSI"
    exchange: "BOK"
    country: "South Korea"
    sheet_name: "SKCCSI"

# Japan
  - input_path: "data_lake/macro/Japan/Japan CPI YoY.xlsx"
    output_path: "data_warehouse/raw/macro/Japan/JPCPIYOY.parquet"
    symbol: "JPCPIYOY"
    exchange: "SBOJ"
    country: "Japan"
    sheet_name: "JPCPIYOY"
  - input_path: "data_lake/macro/Japan/Japan CPI YoY.xlsx"
    output_path: "data_warehouse/raw/macro/Japan/JCPNEFEY.parquet"
    symbol: "JCPNEFEY"
    exchange: "SBOJ"
    country: "Japan"
    sheet_name: "JCPNEFEY"
  - input_path: "data_lake/macro/Japan/Japan Interest Rate.xlsx"
    output_path: "data_warehouse/raw/macro/Japan/BOJDTR.parquet"
    symbol: "BOJDTR"
    exchange: "BOJ"
    country: "Japan"
    sheet_name: "BOJDTR"
  - input_path: "data_lake/macro/Japan/Production.xlsx"
    output_path: "data_warehouse/raw/macro/Japan/PITLJMOM.parquet"
    symbol: "PITLJMOM"
    exchange: "METI"
    country: "Japan"
    sheet_name: "PITLJMOM"

# China
  - input_path: "data_lake/macro/China/China CPI.xlsx"
    output_path: "data_warehouse/raw/macro/China/CNCPIYOY.parquet"
    symbol: "CNCPIYOY"
    exchange: "BOS"
    country: "China"
  - input_path: "data_lake/macro/China/China PMI.xlsx"
    output_path: "data_warehouse/raw/macro/China/CPMINDX.parquet"
    symbol: "CPMINDX"
    exchange: "CFLP"
    country: "China"
  - input_path: "data_lake/macro/China/China PMI.xlsx"
    output_path: "data_warehouse/raw/macro/China/CPMINMNS.parquet"
    symbol: "CPMINMNS"
    exchange: "CFLP"
    country: "China"
  - input_path: "data_lake/macro/China/Caixin PMI.xlsx"
    output_path: "data_warehouse/raw/macro/China/CAIXINPMI.parquet"
    symbol: "CAIXINPMI"
    exchange: "CAIXIN"
    country: "China"
    sheet_name: "CAIXINPMI"