macro_jobs:
  - input_path: "data/macro/USA/USCPI YoY.xlsx"
    output_path: "data_lake/raw/macro/USA/USCPI_YoY.parquet"
    symbol: "CPIYOY"
    exchange: "BOL"
    country: "United States"
  - input_path: "data/macro/USA/Nonfarm Payrolls.xlsx"
    output_path: "data_lake/raw/macro/USA/Nonfarm_Payrolls.parquet"
    symbol: "PAYEMS"
    exchange: "BOL"
    country: "United States"
  - input_path: "data/macro/USA/USPMI.xlsx"
    output_path: "data_lake/raw/macro/USA/NAPMPMI.parquet"
    symbol: "NAPMPMI"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMPMI"
  - input_path: "data/macro/USA/USPMI.xlsx"
    output_path: "data_lake/raw/macro/USA/NAPMNEWO.parquet"
    symbol: "NAPMNEWO"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNEWO"
  - input_path: "data/macro/USA/USPMI.xlsx"
    output_path: "data_lake/raw/macro/USA/NAPMNMI.parquet"
    symbol: "NAPMNMI"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNMI"
  - input_path: "data/macro/USA/USPMI.xlsx"
    output_path: "data_lake/raw/macro/USA/NAPMNNO.parquet"
    symbol: "NAPMNNO"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNNO"
  - input_path: "data/macro/USA/USPMI.xlsx"
    output_path: "data_lake/raw/macro/USA/NAPMNSD.parquet"
    symbol: "NAPMNSD"
    exchange: "ISM"
    country: "United States"
    sheet_name: "NAPMNSD"
  - input_path: "data/macro/Japan/Japan CPI YoY.xlsx"
    output_path: "data_lake/raw/macro/Japan/JPCPIYOY.parquet"
    symbol: "JPCPIYOY"
    exchange: "INDEX"
    country: "Japan"
  - input_path: "data/macro/China/China CPI.xlsx"
    output_path: "data_lake/raw/macro/China/CNCPIYOY.parquet"
    symbol: "CNCPIYOY"
    exchange: "INDEX"
    country: "China"
  - input_path: "data/macro/China/China CPI.xlsx"
    output_path: "data_lake/raw/macro/China/CNCPIYOY.parquet"
    symbol: "CNCPIYOY"
    exchange: "BOS"
    country: "China"
  - input_path: "data/macro/China/China PMI.xlsx"
    output_path: "data_lake/raw/macro/China/CPMINDX.parquet"
    symbol: "CPMINDX"
    exchange: "CFLP"
    country: "China"
  - input_path: "data/macro/USA/ADP Nonfarm Employment changes.xlsx"
    output_path: "data_lake/raw/macro/USA/ADPCHNG.parquet"
    symbol: "ADPCHNG"
    exchange: "ADP"
    country: "United States"
  - input_path: "data/macro/USA/FED Target Rate.xlsx"
    output_path: "data_lake/raw/macro/USA/FDTR.parquet"
    symbol: "FDTR"
    exchange: "FED"
    country: "United States"
  - input_path: "data/macro/USA/US Consumer Confidence.xlsx"
    output_path: "data_lake/raw/macro/USA/CONCCONF.parquet"
    symbol: "CONCCONF"
    exchange: "CB"
    country: "United States"
  - input_path: "data/macro/USA/US Consumer Sentiment.xlsx"
    output_path: "data_lake/raw/macro/USA/CONSSENT.parquet"
    symbol: "CONSSENT"
    exchange: "MICHIGAN"
    country: "United States"
  - input_path: "data/macro/USA/US PCE.xlsx"
    output_path: "data_lake/raw/macro/USA/PCECYOY.parquet"
    symbol: "PCECYOY"
    exchange: "BEA"
    country: "United States"
    sheet_name: "PCECYOY"
  - input_path: "data/macro/USA/US Unemployment rate.xlsx"
    output_path: "data_lake/raw/macro/USA/USURTOT.parquet"
    symbol: "USURTOT"
    exchange: "BOL"
    country: "United States"
  - input_path: "data/macro/USA/USGDP.xlsx"
    output_path: "data_lake/raw/macro/USA/GDPCQQQ.parquet"
    symbol: "GDPCQQQ"
    exchange: "BEA"
    country: "United States"